services:
  qemu:
    image: multiarch/qemu-user-static
    privileged: true
    command: --reset -p yes

  arm:
    build:
      context: .
      args:
        LIBCAMERA_VERSION: 0~git20230302+923f5d70-1
    image: pi-camera
    volumes:
      - ${PWD}:/workdir:rw
    working_dir: /workdir
    tty: true
