services:
  qemu:
    command: --reset -p yes
    image: multiarch/qemu-user-static
    network_mode: default
    privileged: true

  pi-camera:
    image: matefarkas/pi-camera:latest
    build:
      context: .
      target: deployer
    network_mode: default
    volumes:
      - ./:/workdir/:rw
    working_dir: /workdir
    tty: true

  dev-libs:
    build:
      context: .
      target: DEV_LIBS
    network_mode: default
    volumes:
      - ${PWD}:/workdir:rw
    working_dir: /workdir
    tty: true
