services:
  qemu:
    image: multiarch/qemu-user-static
    privileged: true
    command: --reset -p yes

  builder:
    build: .
    image: build-libcamera-eink
    volumes:
      - ${PWD}:/workdir:rw
    working_dir: /workdir
    tty: true

  dev:
    build:
      context: .
      args:
        image: debian:bullseye
    image: dev-libcamera-eink
    volumes:
      - ${PWD}:/workdir:rw
    working_dir: /workdir
    tty: true

  linter:
    build: .linter
    volumes:
      - ${PWD}:/workdir:rw
    working_dir: /workdir
    user: "${UID:-1000}:${GID:-1000}"
