services:
  qemu:
    image: multiarch/qemu-user-static
    privileged: true
    command: --reset -p yes

  arm:
    build: .
    image: pi-camera
    volumes:
      - ${PWD}:/workdir:rw
    working_dir: /workdir
    tty: true
