services:
  qemu:
    command: --reset -p yes
    image: multiarch/qemu-user-static
    network_mode: default
    privileged: true

  arm64:
    build:
      context: .
      target: DEPLOYER
    image: pi-camera
    network_mode: default
    volumes:
      - ${PWD}:/workdir:rw
    working_dir: /workdir
    tty: true
